### ISSUE TITLE
Pinterest style layout

### ISSUE THREAD

**Issue by heartyoh** [heartyoh/cooking-mean#1]
사진의 비율에 따라, 높이가 다른 형태를 지원하도록 참조와 같은 리스트 레이아웃이 좋겠습니다.
http://www.queness.com/post/11133/the-famous-pinterest-dynamic-grid-layout-and-design-inspirations

**Comment by hoppaang** [comment]
시도는 해봤었으나 길이가 상이한 카드리스트가 자연스럽게 정열되지 못하고, 분위기잡는데 중요한 카드별 썸네일 퀄리티가 제각각이라 예상한 효과를 내지 못해 반영되지 않았음
